#include <stdio.h>
#include <stdlib.h>
#include "math.h"
#include <assert.h>
#define RK_V 2.0
#define TEMP 1.0
#define CUTOFF_FAC 100.0
double tol;
double rk_v;
double temperature;
int *loopstack;
int *lvisits;
double *xpos,*ypos;
int binsize;
int binno;
int *pedges_i;
int *pedges_j;
int nedges;
int net_charge;
int *charge;
int *orien;
int *vptr,*fnbr;
int *edgemap;
int fugacity;
double *mmcorr;
double *tmmcorr;
double *ddcorr;
double *ccorr;
double corr1,corr2;
int *match;
int *sitetype;
int nloops;
int nsloops;
int nsloopctr;
double looplen;
double slooplen;
char bindfname[250];
char binmfname[250];
char bincorrfname[250];
char bindorienfname[250];
char binplaqfname[250];
double *mdensity;
double *ddensity;
double n_flippable;
double n_flippable2;
int tot_plaqs;
double dorien[5];
double *lcounts;
double lspace;
int n_vtx;
int nmeasure;
double *probtab;
int ptab_start[9];

