#include <stdio.h>
#include <stdlib.h>
#include "math.h"
#include <assert.h>
#define RK_V -0.5
double tol;
double rk_v;
double *xpos,*ypos;
int binsize;
int binno;
int *pedges_i;
int *pedges_j;
int nedges;
int net_charge;
int *charge;
int *orien;
int *vptr,*fnbr;
int *edgemap;
int fugacity;
double *mmcorr;
double *tmmcorr;
double *ddcorr;
double *ccorr;
double corr1,corr2;
int *match;
int *sitetype;
int nloops;
double looplen;
char bindfname[250];
char binmfname[250];
char bincorrfname[250];
char bindorienfname[250];
char binplaqfname[250];
double *mdensity;
double *ddensity;
int n_flippable;
double dorien[5];
double *lcounts;
double lspace;
int n_vtx;
int nmeasure;
double *probtab;
int ptab_start[9];
